version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: ecommerce_db
    restart: always
    environment:
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: shopuser
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./ecommerce.sql:/docker-entrypoint-initdb.d/ecommerce.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  web:
    build: .
    container_name: ecommerce_web
    restart: always
    ports:
      - "8080:5000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - FLASK_ENV=development
    volumes:
      - ./flask_session:/app/flask_session

volumes:
  mysql_data:
